# Generated by Django 5.1.1 on 2024-09-06 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nome',
        ),
        migrations.AddField(
            model_name='usuario',
            name='kcal',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='altura',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='idade',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='peso',
            field=models.FloatField(default=0),
        ),
    ]
