# Generated by Django 5.1.1 on 2024-09-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tmb', '0003_usuario_sexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')], default='Masculino', max_length=10),
        ),
    ]
